language: node_js
node_js:
- 12.10.0
brancher:
  only:
  - dev
  - master
install:
- npm install
- npm run build
deploy:
  skip_cleanup: true
before_install:
- openssl aes-256-cbc -K $encrypted_cf3c7ff26727_key -iv $encrypted_cf3c7ff26727_iv
  -in id_rsa_ali.enc -out ~\/.ssh/id_rsa_ali -d
